export const initialState = {
  products: [
    {
      id: '1',
      title: 'Nazwa produktu',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'https://thumbs.dreamstime.com/b/blank-white-t-shirt-wood-background-front-template-mockup-73912950.jpg',
    },
    {
      id: '2',
      title: 'Nazwa produktu',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '33,33',
      image: 'https://thumbs.dreamstime.com/b/man-black-t-shirt-slim-tall-posing-title-social-network-addict-34226905.jpg',
    },
    {
      id: '3',
      title: 'Nazwa produktu',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'src do zdjecia',
    },
    {
      id: '4',
      title: 'Nazwa produktu',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'src do zdjecia',
    },
    {
      id: '5',
      title: 'Nazwa produktu',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'src do zdjecia',
    },
    {
      id: '6',
      title: 'Nazwa produktu',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'src do zdjecia',
    },
    {
      id: '7',
      title: 'Nazwa produktu',
      category: 'Hoodie',
      description: 'Opis produktu',
      price: '21,15',
      image: 'src do zdjecia',
    },
    {
      id: '8',
      title: 'Nazwa produktu',
      category: 'Hoodie',
      description: 'Opis produktu',
      price: '33,33',
      image: 'src do zdjecia',
    },
  ],

  loading: {
    active: false,
    error: false,
  },
};
