export const initialState = {
  products: [
    {
      id: '1',
      title: 'Lorem Ipsum',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'https://thumbs.dreamstime.com/b/blank-white-t-shirt-wood-background-front-template-mockup-73912950.jpg',
    },
    {
      id: '2',
      title: 'Lorem Ipsum',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '33,33',
      image: 'https://thumbs.dreamstime.com/b/man-black-t-shirt-slim-tall-posing-title-social-network-addict-34226905.jpg',
    },
    {
      id: '3',
      title: 'Lorem Ipsum',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'https://thumbs.dreamstime.com/b/dark-grey-t-shirt-isolated-white-background-wall-57405408.jpg',
    },
    {
      id: '4',
      title: 'Lorem Ipsum',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'https://thumbs.dreamstime.com/b/mockup-template-man-s-t-shirt-color-white-background-126850413.jpg',
    },
    {
      id: '5',
      title: 'Lorem Ipsum',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'https://thumbs.dreamstime.com/b/muscular-man-wearing-grey-t-shirt-close-up-blank-58969553.jpg',
    },
    {
      id: '6',
      title: 'Lorem Ipsum',
      category: 'T-shirt',
      description: 'Opis produktu',
      price: '21,15',
      image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: '7',
      title: 'Lorem Ipsum',
      category: 'Hoodie',
      description: 'Opis produktu',
      price: '21,15',
      image: 'https://images.unsplash.com/photo-1530576423176-a783f6df10f0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: '8',
      title: 'Lorem Ipsum',
      category: 'Hoodie',
      description: 'Opis produktu',
      price: '33,33',
      image: 'https://images.unsplash.com/photo-1579269896398-4deb6cbdc320?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
    },
  ],

  loading: {
    active: false,
    error: false,
  },
};
